shell /opt/homebrew/bin/fish

font_family      Maple Mono NF
font_size        15.0

macos_option_as_alt both

cursor_shape block
cursor_trail 1
cursor_trail_start_threshold 0
shell_integration no-cursor
cursor #f9e2af
cursor_text_color #18191a
# cursor_trail 3
cursor_blink_interval 0

remember_window_size no
initial_window_width  120c
initial_window_height 50c
window_padding_width 5
hide_window_decorations titlebar-only
macos_show_window_title_in menubar
macos_menubar_title_max_length 60

enabled_layouts splits,stack,tall,fat,grid

window_border_width 1pt
window_title_bar_min_windows 2
active_border_color #f9e2af
inactive_border_color #3c4048

tab_bar_edge top
tab_bar_style separator
tab_separator " | "
tab_bar_align center
tab_bar_margin_width 5.0
tab_title_max_length 24
active_tab_font_style bold
tab_title_template "{index}:{title.strip().lstrip(':').strip()}"
window_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.window}{progress_percent}{title.strip().lstrip(':').strip()}"
tab_bar_background #18191a
active_tab_foreground   #232425
active_tab_background   #f9e2af
inactive_tab_foreground #cdcdcd
inactive_tab_background #18191a

background #18191a
foreground #cdcdcd
selection_background #3c4048
selection_foreground #cdcdcd

color0  #232425
color1  #d2788c
color2  #a6e3a1
color3  #f9e2af
color4  #94e2d5
color5  #baa0f8
color6  #94e2d5
color7  #cdcdcd
color8  #3c4048
color9  #d2788c
color10 #a6e3a1
color11 #f9e2af
color12 #94e2d5
color13 #baa0f8
color14 #94e2d5
color15 #e4e4e4

scrollback_lines 100000

copy_on_select yes
mouse_hide_wait -1

map ctrl+alt+right launch --location=vsplit --cwd=current
map ctrl+alt+left  launch --location=vsplit --cwd=current
map ctrl+alt+down  launch --location=hsplit --cwd=current
map ctrl+alt+up    launch --location=hsplit --cwd=current

map alt+left  neighboring_window left
map alt+right neighboring_window right
map alt+up    neighboring_window up
map alt+down  neighboring_window down

map ctrl+alt+shift+left  resize_window narrower 5
map ctrl+alt+shift+right resize_window wider 5
map ctrl+alt+shift+up    resize_window taller 5
map ctrl+alt+shift+down  resize_window shorter 5

map ctrl+alt+shift+l toggle_layout stack

map ctrl+shift+t new_tab_with_cwd
map cmd+, edit_config_file
